# Docker File for Deploying the train system

FROM ubuntu:focal
ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /app
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y install python3-pip
RUN apt-get install -y ffmpeg libsm6  libxext6

# For additional requirements please copy optional_requirements too 
# For base apps the step mentioned in above comment is not necessary
COPY requirements.txt .
RUN pip3 install -r requirements.txt
COPY . .
# Please don't forget to add wandb token 
# or any other sort of authentication

RUN python3 setup.py
ENTRYPOINT [ "python3 train.py" ]
